<?php
/** @var Zend\Form\Form $form */
$form = $this->myForm;
?>
<?= $this->form()->openTag($form); ?>
  <div class="form-group">
    <?= $this->formLabel($form->get('name')); ?>
    <?= $this->formElement($form->get('name')); ?>
    <?= $this->formElementErrors($form->get('name')); ?>
  </div>
  <div class="form-group">
    <?= $this->formLabel($form->get('comment')); ?>
    <?= $this->formElement($form->get('comment')); ?>
    <?= $this->formElementErrors($form->get('comment')); ?>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <?= $this->formElement($form->get('submit')); ?>
    </div>
  </div>
<?= $this->form()->closeTag();
